project_id = "uyyjpzfdkfdopyrerpyl"

[functions.midtrans-qris]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/midtrans-qris/index.ts"

[functions.midtrans-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/midtrans-webhook/index.ts"

[functions.hello-world]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/hello-world/index.ts"
