project_id = "kmrspgxokybuqgcnxzkj"
[functions.midtrans-qris]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/midtrans-qris/index.ts"

[functions.midtrans-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/midtrans-webhook/index.ts"

[functions.hello-world]
enabled = true
verify_jwt = true
import_map = "./functions/hello-world/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hello-world/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hello-world/*.html" ]
